-- 006_ensure_pets_columns.sql — ensure pets has all columns the code expects.
ALTER TABLE pets ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS ticker TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS traits JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS bio TEXT NOT NULL DEFAULT '';
ALTER TABLE pets ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS creator_wallet TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS launch_signature TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS pet_wallet_pubkey TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS pet_wallet_encrypted TEXT;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
